[changelog]
header = """
# Changelog\n
"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} by @{{ commit.author.name }}\
{% endfor %}
{% endfor %}
{% if previous.version %}
**Full Changelog**: [{{ previous.version }}...{{ version }}](https://github.com/John710/kompoz/compare/{{ previous.version }}...{{ version }})
{% endif %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^chore\\(release\\)", skip = true },
  { message = "^release:", skip = true },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^ci", group = "CI/CD" },
  { message = "^docs", group = "Documentation" },
  { message = "^chore", group = "Chores" },
  { message = "^test", group = "Testing" },
  { message = "^security", group = "Security" },
]
filter_commits = false
tag_pattern = "^v?[0-9]+\\.[0-9]+\\.[0-9]+.*$"
sort_commits = "newest"
